### ISSUE TITLE
Is this add-on still being maintained and will it be updated for Python 3?

### ISSUE THREAD

**Issue by britechguy** [javidominguez/DragAndDrop#2]
The subject pretty much says it all.  Since this add-on appears to have last been worked on in 2016 it is likely to break in the near future with the latest version of NVDA.

Since I don't code in Python, I have no idea how complex updating this would be.  If the original developer is not maintaining it, can maintenance fall to anyone else who might be interested?

**Comment by javidominguez** [comment]
I have already updated it. Now it works in NVDA 2019.3.
View dev branch https://github.com/javidominguez/DragAndDrop/tree/dev
or latest release https://github.com/javidominguez/DragAndDrop/releases/tag/2.0dev

**Comment by britechguy** [comment]
Thanks much for taking the time to reply and for having done the update!
