### ISSUE TITLE
README.md file has incorrect formatting when converted to html

### ISSUE THREAD

**Issue by tmthywynn8** [javidominguez/DragAndDrop#3]
When the html file is generated from [README.md](https://github.com/javidominguez/DragAndDrop/blob/master/README.md), there are two things that do not convert over from the markdown formatting:

1. The table of hotkeys: I suspect this is because the header cells have only one dash (-) instead of at least three.
2. The options  for drop: The list items are not correctly formatted as there needs to be a blank line before the start of the list.
3. There may be an extra blank line before the options  for drop, but I am not sure if that is a deliberate decision or not.

**Comment by cary-rowen** [comment]
Hi, @javidominguez 

I think you may need to update to the latest add-on template. The new add-on template supports adding markdown extensions and may fix the form rendering problem. If you agree, I can submit a PR.

Thanks!

**Comment by javidominguez** [comment]
Hello. Yes of course, thanks.
